### PR TITLE
Add AWS Command Line Tools (CLI)

### PR DESCRIPTION
**Pull request by bluerogue251**
Add AWS CLI and get rid of some stuff nobody is using.

### CODE REVIEW

**Comment by NicoDeVeaux** [comment]
were we ever planning on using redis? or is that just there by default?

**Comment by rassaby** [comment]
:+1:

**Comment by bluerogue251** [comment]
Redis was left over from the company we forked this from. We are not currently using it. When we do start to use things like Redis we should get them from docker instead of installing them straight on our macs.

**Comment by NicoDeVeaux** [comment]
LGTM

**Pull request merged**
